registry_entries:
- tasks/composeobj_001__first_put_the_milk_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_butter_in_the_basket/registry_entry.yaml
- tasks/composeobj_002__first_put_the_milk_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/composeobj_003__first_put_the_milk_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_ketchup_in_the_basket/registry_entry.yaml
- tasks/composeobj_004__first_put_the_milk_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_orange_juice_in_the_basket/registry_entry.yaml
- tasks/composeobj_005__first_put_the_milk_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_tomato_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_006__first_put_the_milk_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/composeobj_007__first_put_the_milk_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_ketchup_in_the_basket/registry_entry.yaml
- tasks/composeobj_008__first_put_the_milk_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_orange_juice_in_the_basket/registry_entry.yaml
- tasks/composeobj_009__first_put_the_milk_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_tomato_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_010__first_put_the_milk_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_ketchup_in_the_basket/registry_entry.yaml
- tasks/composeobj_011__first_put_the_milk_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_orange_juice_in_the_basket/registry_entry.yaml
- tasks/composeobj_012__first_put_the_milk_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_tomato_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_013__first_put_the_milk_in_the_basket_then_put_the_ketchup_in_the_basket_and_finally_put_the_orange_juice_in_the_basket/registry_entry.yaml
- tasks/composeobj_014__first_put_the_milk_in_the_basket_then_put_the_ketchup_in_the_basket_and_finally_put_the_tomato_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_015__first_put_the_milk_in_the_basket_then_put_the_orange_juice_in_the_basket_and_finally_put_the_tomato_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_016__first_put_the_milk_in_the_basket_then_put_the_alphabet_soup_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_cream_cheese_box_in_th/registry_entry.yaml
- tasks/composeobj_017__first_put_the_milk_in_the_basket_then_put_the_alphabet_soup_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_ketchup_in_the_basket/registry_entry.yaml
- tasks/composeobj_018__first_put_the_milk_in_the_basket_then_put_the_alphabet_soup_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_orange_juice_in_the_ba/registry_entry.yaml
- tasks/composeobj_019__first_put_the_milk_in_the_basket_then_put_the_alphabet_soup_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_tomato_sauce_in_the_ba/registry_entry.yaml
- tasks/composeobj_020__first_put_the_milk_in_the_basket_then_put_the_alphabet_soup_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_ketchup_in_t/registry_entry.yaml
- tasks/composeobj_021__first_put_the_milk_in_the_basket_then_put_the_alphabet_soup_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_orange_juice/registry_entry.yaml
- tasks/composeobj_022__first_put_the_milk_in_the_basket_then_put_the_alphabet_soup_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_tomato_sauce/registry_entry.yaml
- tasks/composeobj_023__first_put_the_milk_in_the_basket_then_put_the_alphabet_soup_in_the_basket_then_put_the_ketchup_in_the_basket_and_finally_put_the_orange_juice_in_the_b/registry_entry.yaml
- tasks/composeobj_024__first_put_the_milk_in_the_basket_then_put_the_alphabet_soup_in_the_basket_then_put_the_ketchup_in_the_basket_and_finally_put_the_tomato_sauce_in_the_b/registry_entry.yaml
- tasks/composeobj_025__first_put_the_milk_in_the_basket_then_put_the_alphabet_soup_in_the_basket_then_put_the_orange_juice_in_the_basket_and_finally_put_the_tomato_sauce_in/registry_entry.yaml
- tasks/composeobj_026__first_put_the_milk_in_the_basket_then_put_the_butter_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_ketchup_in_the_bask/registry_entry.yaml
- tasks/composeobj_027__first_put_the_milk_in_the_basket_then_put_the_butter_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_orange_juice_in_the/registry_entry.yaml
- tasks/composeobj_028__first_put_the_milk_in_the_basket_then_put_the_butter_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_tomato_sauce_in_the/registry_entry.yaml
- tasks/composeobj_029__first_put_the_milk_in_the_basket_then_put_the_butter_in_the_basket_then_put_the_ketchup_in_the_basket_and_finally_put_the_orange_juice_in_the_basket/registry_entry.yaml
- tasks/composeobj_030__first_put_the_milk_in_the_basket_then_put_the_butter_in_the_basket_then_put_the_ketchup_in_the_basket_and_finally_put_the_tomato_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_031__first_put_the_milk_in_the_basket_then_put_the_butter_in_the_basket_then_put_the_orange_juice_in_the_basket_and_finally_put_the_tomato_sauce_in_the_bas/registry_entry.yaml
- tasks/composeobj_032__first_put_the_milk_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_then_put_the_ketchup_in_the_basket_and_finally_put_the_orange_juice_in_th/registry_entry.yaml
- tasks/composeobj_033__first_put_the_milk_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_then_put_the_ketchup_in_the_basket_and_finally_put_the_tomato_sauce_in_th/registry_entry.yaml
- tasks/composeobj_034__first_put_the_milk_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_then_put_the_orange_juice_in_the_basket_and_finally_put_the_tomato_sauce/registry_entry.yaml
- tasks/composeobj_035__first_put_the_milk_in_the_basket_then_put_the_ketchup_in_the_basket_then_put_the_orange_juice_in_the_basket_and_finally_put_the_tomato_sauce_in_the_ba/registry_entry.yaml
- tasks/composeobj_036__put_the_alphabet_soup_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/composeobj_037__put_the_alphabet_soup_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_ketchup_in_the_basket/registry_entry.yaml
- tasks/composeobj_038__put_the_alphabet_soup_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_orange_juice_in_the_basket/registry_entry.yaml
- tasks/composeobj_039__put_the_alphabet_soup_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_tomato_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_040__put_the_alphabet_soup_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_ketchup_in_the_basket/registry_entry.yaml
- tasks/composeobj_041__put_the_alphabet_soup_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_orange_juice_in_the_basket/registry_entry.yaml
- tasks/composeobj_042__put_the_alphabet_soup_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_tomato_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_043__put_the_alphabet_soup_in_the_basket_then_put_the_ketchup_in_the_basket_and_finally_put_the_orange_juice_in_the_basket/registry_entry.yaml
- tasks/composeobj_044__put_the_alphabet_soup_in_the_basket_then_put_the_ketchup_in_the_basket_and_finally_put_the_tomato_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_045__put_the_alphabet_soup_in_the_basket_then_put_the_orange_juice_in_the_basket_and_finally_put_the_tomato_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_046__put_the_butter_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_ketchup_in_the_basket/registry_entry.yaml
- tasks/composeobj_047__put_the_butter_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_orange_juice_in_the_basket/registry_entry.yaml
- tasks/composeobj_048__put_the_butter_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_tomato_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_049__put_the_butter_in_the_basket_then_put_the_ketchup_in_the_basket_and_finally_put_the_orange_juice_in_the_basket/registry_entry.yaml
- tasks/composeobj_050__put_the_butter_in_the_basket_then_put_the_ketchup_in_the_basket_and_finally_put_the_tomato_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_051__put_the_butter_in_the_basket_then_put_the_orange_juice_in_the_basket_and_finally_put_the_tomato_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_052__put_the_cream_cheese_box_in_the_basket_then_put_the_ketchup_in_the_basket_and_finally_put_the_orange_juice_in_the_basket/registry_entry.yaml
- tasks/composeobj_053__put_the_cream_cheese_box_in_the_basket_then_put_the_ketchup_in_the_basket_and_finally_put_the_tomato_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_054__put_the_cream_cheese_box_in_the_basket_then_put_the_orange_juice_in_the_basket_and_finally_put_the_tomato_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_055__put_the_ketchup_in_the_basket_then_put_the_orange_juice_in_the_basket_and_finally_put_the_tomato_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_056__put_the_alphabet_soup_in_the_basket_then_put_the_butter_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_ketchup_in_the_b/registry_entry.yaml
- tasks/composeobj_057__put_the_alphabet_soup_in_the_basket_then_put_the_butter_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_orange_juice_in/registry_entry.yaml
- tasks/composeobj_058__put_the_alphabet_soup_in_the_basket_then_put_the_butter_in_the_basket_then_put_the_tomato_sauce_in_the_basket_and_finally_put_the_cream_cheese_box_in/registry_entry.yaml
- tasks/composeobj_059__put_the_alphabet_soup_in_the_basket_then_put_the_butter_in_the_basket_then_put_the_ketchup_in_the_basket_and_finally_put_the_orange_juice_in_the_baske/registry_entry.yaml
- tasks/composeobj_060__put_the_alphabet_soup_in_the_basket_then_put_the_butter_in_the_basket_then_put_the_tomato_sauce_in_the_basket_and_finally_put_the_ketchup_in_the_baske/registry_entry.yaml
- tasks/composeobj_061__put_the_alphabet_soup_in_the_basket_then_put_the_butter_in_the_basket_then_put_the_tomato_sauce_in_the_basket_and_finally_put_the_orange_juice_in_the/registry_entry.yaml
- tasks/composeobj_062__put_the_alphabet_soup_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_then_put_the_ketchup_in_the_basket_and_finally_put_the_orange_juice_in/registry_entry.yaml
- tasks/composeobj_063__put_the_alphabet_soup_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_then_put_the_ketchup_in_the_basket_and_finally_put_the_tomato_sauce_in/registry_entry.yaml
- tasks/composeobj_064__put_the_alphabet_soup_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_then_put_the_orange_juice_in_the_basket_and_finally_put_the_tomato_sau/registry_entry.yaml
- tasks/composeobj_065__put_the_alphabet_soup_in_the_basket_then_put_the_ketchup_in_the_basket_then_put_the_orange_juice_in_the_basket_and_finally_put_the_tomato_sauce_in_the/registry_entry.yaml
- tasks/composeobj_066__put_the_butter_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_then_put_the_ketchup_in_the_basket_and_finally_put_the_orange_juice_in_the_ba/registry_entry.yaml
- tasks/composeobj_067__put_the_butter_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_then_put_the_ketchup_in_the_basket_and_finally_put_the_tomato_sauce_in_the_ba/registry_entry.yaml
- tasks/composeobj_068__put_the_butter_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_then_put_the_orange_juice_in_the_basket_and_finally_put_the_tomato_sauce_in_t/registry_entry.yaml
- tasks/composeobj_069__put_the_butter_in_the_basket_then_put_the_ketchup_in_the_basket_then_put_the_orange_juice_in_the_basket_and_finally_put_the_tomato_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_070__put_the_cream_cheese_box_in_the_basket_then_put_the_ketchup_in_the_basket_then_put_the_orange_juice_in_the_basket_and_finally_put_the_tomato_sauce_in/registry_entry.yaml
- tasks/composeobj_071__put_the_alphabet_soup_in_the_basket_then_put_the_butter_in_the_basket_then_put_the_tomato_sauce_in_the_basket_and_finally_put_the_cream_cheese_box_in/registry_entry.yaml
- tasks/composeobj_072__put_the_alphabet_soup_in_the_basket_then_put_the_butter_in_the_basket_then_put_the_tomato_sauce_in_the_basket_and_finally_put_the_ketchup_in_the_baske/registry_entry.yaml
- tasks/composeobj_073__put_the_alphabet_soup_in_the_basket_then_put_the_butter_in_the_basket_then_put_the_tomato_sauce_in_the_basket_and_finally_put_the_orange_juice_in_the/registry_entry.yaml
- tasks/composeobj_074__first_put_the_milk_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_salad_dressing_in_the_basket/registry_entry.yaml
- tasks/composeobj_075__first_put_the_milk_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/composeobj_076__first_put_the_milk_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_tomato_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_077__first_put_the_milk_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_butter_in_the_basket/registry_entry.yaml
- tasks/composeobj_078__first_put_the_milk_in_the_basket_then_put_the_salad_dressing_in_the_basket_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/composeobj_079__first_put_the_milk_in_the_basket_then_put_the_salad_dressing_in_the_basket_and_finally_put_the_tomato_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_080__first_put_the_milk_in_the_basket_then_put_the_salad_dressing_in_the_basket_and_finally_put_the_butter_in_the_basket/registry_entry.yaml
- tasks/composeobj_081__first_put_the_milk_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_tomato_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_082__first_put_the_milk_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_butter_in_the_basket/registry_entry.yaml
- tasks/composeobj_083__first_put_the_milk_in_the_basket_then_put_the_tomato_sauce_in_the_basket_and_finally_put_the_butter_in_the_basket/registry_entry.yaml
- tasks/composeobj_084__first_put_the_milk_in_the_basket_then_put_the_alphabet_soup_in_the_basket_then_put_the_salad_dressing_in_the_basket_and_finally_put_the_cream_cheese_b/registry_entry.yaml
- tasks/composeobj_085__first_put_the_milk_in_the_basket_then_put_the_alphabet_soup_in_the_basket_then_put_the_salad_dressing_in_the_basket_and_finally_put_the_tomato_sauce_i/registry_entry.yaml
- tasks/composeobj_086__first_put_the_milk_in_the_basket_then_put_the_alphabet_soup_in_the_basket_then_put_the_salad_dressing_in_the_basket_and_finally_put_the_butter_in_the/registry_entry.yaml
- tasks/composeobj_087__first_put_the_milk_in_the_basket_then_put_the_alphabet_soup_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_tomato_sauce/registry_entry.yaml
- tasks/composeobj_088__first_put_the_milk_in_the_basket_then_put_the_alphabet_soup_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_butter_in_th/registry_entry.yaml
- tasks/composeobj_089__first_put_the_milk_in_the_basket_then_put_the_alphabet_soup_in_the_basket_then_put_the_tomato_sauce_in_the_basket_and_finally_put_the_butter_in_the_ba/registry_entry.yaml
- tasks/composeobj_090__first_put_the_milk_in_the_basket_then_put_the_salad_dressing_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_tomato_sauc/registry_entry.yaml
- tasks/composeobj_091__first_put_the_milk_in_the_basket_then_put_the_salad_dressing_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_butter_in_t/registry_entry.yaml
- tasks/composeobj_092__first_put_the_milk_in_the_basket_then_put_the_salad_dressing_in_the_basket_then_put_the_tomato_sauce_in_the_basket_and_finally_put_the_butter_in_the_b/registry_entry.yaml
- tasks/composeobj_093__first_put_the_milk_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_then_put_the_tomato_sauce_in_the_basket_and_finally_put_the_butter_in_the/registry_entry.yaml
- tasks/composeobj_094__put_the_alphabet_soup_in_the_basket_then_put_the_salad_dressing_in_the_basket_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/composeobj_095__put_the_alphabet_soup_in_the_basket_then_put_the_salad_dressing_in_the_basket_and_finally_put_the_tomato_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_096__put_the_alphabet_soup_in_the_basket_then_put_the_salad_dressing_in_the_basket_and_finally_put_the_butter_in_the_basket/registry_entry.yaml
- tasks/composeobj_097__put_the_alphabet_soup_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_tomato_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_098__put_the_alphabet_soup_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_butter_in_the_basket/registry_entry.yaml
- tasks/composeobj_099__put_the_alphabet_soup_in_the_basket_then_put_the_tomato_sauce_in_the_basket_and_finally_put_the_butter_in_the_basket/registry_entry.yaml
- tasks/composeobj_100__put_the_salad_dressing_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_tomato_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_101__put_the_salad_dressing_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_butter_in_the_basket/registry_entry.yaml
- tasks/composeobj_102__put_the_salad_dressing_in_the_basket_then_put_the_tomato_sauce_in_the_basket_and_finally_put_the_butter_in_the_basket/registry_entry.yaml
- tasks/composeobj_103__put_the_cream_cheese_box_in_the_basket_then_put_the_tomato_sauce_in_the_basket_and_finally_put_the_butter_in_the_basket/registry_entry.yaml
- tasks/composeobj_104__put_the_alphabet_soup_in_the_basket_then_put_the_salad_dressing_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_tomato_s/registry_entry.yaml
- tasks/composeobj_105__put_the_alphabet_soup_in_the_basket_then_put_the_salad_dressing_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_butter_i/registry_entry.yaml
- tasks/composeobj_106__put_the_alphabet_soup_in_the_basket_then_put_the_salad_dressing_in_the_basket_then_put_the_tomato_sauce_in_the_basket_and_finally_put_the_butter_in_th/registry_entry.yaml
- tasks/composeobj_107__put_the_alphabet_soup_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_then_put_the_tomato_sauce_in_the_basket_and_finally_put_the_butter_in/registry_entry.yaml
- tasks/composeobj_108__put_the_salad_dressing_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_then_put_the_tomato_sauce_in_the_basket_and_finally_put_the_butter_in/registry_entry.yaml
- tasks/composeobj_109__first_put_the_milk_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_alphabet_soup_in_the_basket/registry_entry.yaml
- tasks/composeobj_110__first_put_the_milk_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_tomato_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_111__first_put_the_milk_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_butter_in_the_basket/registry_entry.yaml
- tasks/composeobj_112__first_put_the_milk_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_orange_juice_in_the_basket/registry_entry.yaml
- tasks/composeobj_113__first_put_the_milk_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_tomato_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_114__first_put_the_milk_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_butter_in_the_basket/registry_entry.yaml
- tasks/composeobj_115__first_put_the_milk_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_orange_juice_in_the_basket/registry_entry.yaml
- tasks/composeobj_116__first_put_the_milk_in_the_basket_then_put_the_tomato_sauce_in_the_basket_and_finally_put_the_butter_in_the_basket/registry_entry.yaml
- tasks/composeobj_117__first_put_the_milk_in_the_basket_then_put_the_tomato_sauce_in_the_basket_and_finally_put_the_orange_juice_in_the_basket/registry_entry.yaml
- tasks/composeobj_118__first_put_the_milk_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_orange_juice_in_the_basket/registry_entry.yaml
- tasks/composeobj_119__first_put_the_milk_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_tomato_sauce/registry_entry.yaml
- tasks/composeobj_120__first_put_the_milk_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_butter_in_th/registry_entry.yaml
- tasks/composeobj_121__first_put_the_milk_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_orange_juice/registry_entry.yaml
- tasks/composeobj_122__first_put_the_milk_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_then_put_the_tomato_sauce_in_the_basket_and_finally_put_the_butter_in_the/registry_entry.yaml
- tasks/composeobj_123__first_put_the_milk_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_then_put_the_tomato_sauce_in_the_basket_and_finally_put_the_orange_juice/registry_entry.yaml
- tasks/composeobj_124__first_put_the_milk_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_orange_juice_in_the/registry_entry.yaml
- tasks/composeobj_125__first_put_the_milk_in_the_basket_then_put_the_alphabet_soup_in_the_basket_then_put_the_tomato_sauce_in_the_basket_and_finally_put_the_butter_in_the_ba/registry_entry.yaml
- tasks/composeobj_126__first_put_the_milk_in_the_basket_then_put_the_alphabet_soup_in_the_basket_then_put_the_tomato_sauce_in_the_basket_and_finally_put_the_orange_juice_in/registry_entry.yaml
- tasks/composeobj_127__first_put_the_milk_in_the_basket_then_put_the_alphabet_soup_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_orange_juice_in_the_ba/registry_entry.yaml
- tasks/composeobj_128__first_put_the_milk_in_the_basket_then_put_the_tomato_sauce_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_orange_juice_in_the_bas/registry_entry.yaml
- tasks/composeobj_129__first_put_the_milk_in_the_basket_then_put_the_ketchup_in_the_basket_and_finally_put_the_bbq_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_130__first_put_the_milk_in_the_basket_then_put_the_ketchup_in_the_basket_and_finally_put_the_salad_dressing_in_the_basket/registry_entry.yaml
- tasks/composeobj_131__first_put_the_milk_in_the_basket_then_put_the_ketchup_in_the_basket_and_finally_put_the_alphabet_soup_in_the_basket/registry_entry.yaml
- tasks/composeobj_132__first_put_the_milk_in_the_basket_then_put_the_ketchup_in_the_basket_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/composeobj_133__first_put_the_milk_in_the_basket_then_put_the_bbq_sauce_in_the_basket_and_finally_put_the_salad_dressing_in_the_basket/registry_entry.yaml
- tasks/composeobj_134__first_put_the_milk_in_the_basket_then_put_the_bbq_sauce_in_the_basket_and_finally_put_the_alphabet_soup_in_the_basket/registry_entry.yaml
- tasks/composeobj_135__first_put_the_milk_in_the_basket_then_put_the_bbq_sauce_in_the_basket_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/composeobj_136__first_put_the_milk_in_the_basket_then_put_the_salad_dressing_in_the_basket_and_finally_put_the_alphabet_soup_in_the_basket/registry_entry.yaml
- tasks/composeobj_137__first_put_the_milk_in_the_basket_then_put_the_salad_dressing_in_the_basket_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/composeobj_138__first_put_the_milk_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/composeobj_139__first_put_the_milk_in_the_basket_then_put_the_ketchup_in_the_basket_then_put_the_bbq_sauce_in_the_basket_and_finally_put_the_salad_dressing_in_the_bas/registry_entry.yaml
- tasks/composeobj_140__first_put_the_milk_in_the_basket_then_put_the_ketchup_in_the_basket_then_put_the_bbq_sauce_in_the_basket_and_finally_put_the_alphabet_soup_in_the_bask/registry_entry.yaml
- tasks/composeobj_141__first_put_the_milk_in_the_basket_then_put_the_ketchup_in_the_basket_then_put_the_bbq_sauce_in_the_basket_and_finally_put_the_cream_cheese_box_in_the_b/registry_entry.yaml
- tasks/composeobj_142__first_put_the_milk_in_the_basket_then_put_the_ketchup_in_the_basket_then_put_the_salad_dressing_in_the_basket_and_finally_put_the_alphabet_soup_in_the/registry_entry.yaml
- tasks/composeobj_143__first_put_the_milk_in_the_basket_then_put_the_ketchup_in_the_basket_then_put_the_salad_dressing_in_the_basket_and_finally_put_the_cream_cheese_box_in/registry_entry.yaml
- tasks/composeobj_144__first_put_the_milk_in_the_basket_then_put_the_ketchup_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_cream_cheese_box_in_t/registry_entry.yaml
- tasks/composeobj_145__first_put_the_milk_in_the_basket_then_put_the_bbq_sauce_in_the_basket_then_put_the_salad_dressing_in_the_basket_and_finally_put_the_alphabet_soup_in_t/registry_entry.yaml
- tasks/composeobj_146__first_put_the_milk_in_the_basket_then_put_the_bbq_sauce_in_the_basket_then_put_the_salad_dressing_in_the_basket_and_finally_put_the_cream_cheese_box_i/registry_entry.yaml
- tasks/composeobj_147__first_put_the_milk_in_the_basket_then_put_the_bbq_sauce_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_cream_cheese_box_in/registry_entry.yaml
- tasks/composeobj_148__first_put_the_milk_in_the_basket_then_put_the_salad_dressing_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_cream_cheese_b/registry_entry.yaml
- tasks/composeobj_149__put_the_ketchup_in_the_basket_then_put_the_bbq_sauce_in_the_basket_and_finally_put_the_salad_dressing_in_the_basket/registry_entry.yaml
- tasks/composeobj_150__put_the_ketchup_in_the_basket_then_put_the_bbq_sauce_in_the_basket_and_finally_put_the_alphabet_soup_in_the_basket/registry_entry.yaml
- tasks/composeobj_151__put_the_ketchup_in_the_basket_then_put_the_bbq_sauce_in_the_basket_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/composeobj_152__put_the_ketchup_in_the_basket_then_put_the_salad_dressing_in_the_basket_and_finally_put_the_alphabet_soup_in_the_basket/registry_entry.yaml
- tasks/composeobj_153__put_the_ketchup_in_the_basket_then_put_the_salad_dressing_in_the_basket_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/composeobj_154__put_the_ketchup_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/composeobj_155__put_the_bbq_sauce_in_the_basket_then_put_the_salad_dressing_in_the_basket_and_finally_put_the_alphabet_soup_in_the_basket/registry_entry.yaml
- tasks/composeobj_156__put_the_bbq_sauce_in_the_basket_then_put_the_salad_dressing_in_the_basket_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/composeobj_157__put_the_bbq_sauce_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/composeobj_158__put_the_salad_dressing_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/composeobj_159__put_the_ketchup_in_the_basket_then_put_the_bbq_sauce_in_the_basket_then_put_the_salad_dressing_in_the_basket_and_finally_put_the_alphabet_soup_in_the/registry_entry.yaml
- tasks/composeobj_160__put_the_ketchup_in_the_basket_then_put_the_bbq_sauce_in_the_basket_then_put_the_salad_dressing_in_the_basket_and_finally_put_the_cream_cheese_box_in_t/registry_entry.yaml
- tasks/composeobj_161__put_the_ketchup_in_the_basket_then_put_the_bbq_sauce_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_cream_cheese_box_in_th/registry_entry.yaml
- tasks/composeobj_162__put_the_ketchup_in_the_basket_then_put_the_salad_dressing_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_cream_cheese_box/registry_entry.yaml
- tasks/composeobj_163__put_the_bbq_sauce_in_the_basket_then_put_the_salad_dressing_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_cream_cheese_bo/registry_entry.yaml
- tasks/composeobj_164__first_put_the_milk_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_tomato_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_165__first_put_the_milk_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_butter_in_the_basket/registry_entry.yaml
- tasks/composeobj_166__first_put_the_milk_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_orange_juice_in_the_basket/registry_entry.yaml
- tasks/composeobj_167__first_put_the_milk_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_chocolate_pudding_in_the_basket/registry_entry.yaml
- tasks/composeobj_168__first_put_the_milk_in_the_basket_then_put_the_tomato_sauce_in_the_basket_and_finally_put_the_butter_in_the_basket/registry_entry.yaml
- tasks/composeobj_169__first_put_the_milk_in_the_basket_then_put_the_tomato_sauce_in_the_basket_and_finally_put_the_orange_juice_in_the_basket/registry_entry.yaml
- tasks/composeobj_170__first_put_the_milk_in_the_basket_then_put_the_tomato_sauce_in_the_basket_and_finally_put_the_chocolate_pudding_in_the_basket/registry_entry.yaml
- tasks/composeobj_171__first_put_the_milk_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_orange_juice_in_the_basket/registry_entry.yaml
- tasks/composeobj_172__first_put_the_milk_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_chocolate_pudding_in_the_basket/registry_entry.yaml
- tasks/composeobj_173__first_put_the_milk_in_the_basket_then_put_the_orange_juice_in_the_basket_and_finally_put_the_chocolate_pudding_in_the_basket/registry_entry.yaml
- tasks/composeobj_174__first_put_the_milk_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_then_put_the_tomato_sauce_in_the_basket_and_finally_put_the_butter_in_the/registry_entry.yaml
- tasks/composeobj_175__first_put_the_milk_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_then_put_the_tomato_sauce_in_the_basket_and_finally_put_the_orange_juice/registry_entry.yaml
- tasks/composeobj_176__first_put_the_milk_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_then_put_the_tomato_sauce_in_the_basket_and_finally_put_the_chocolate_pud/registry_entry.yaml
- tasks/composeobj_177__first_put_the_milk_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_orange_juice_in_the/registry_entry.yaml
- tasks/composeobj_178__first_put_the_milk_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_chocolate_pudding_i/registry_entry.yaml
- tasks/composeobj_179__first_put_the_milk_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_then_put_the_orange_juice_in_the_basket_and_finally_put_the_chocolate_pud/registry_entry.yaml
- tasks/composeobj_180__first_put_the_milk_in_the_basket_then_put_the_tomato_sauce_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_orange_juice_in_the_bas/registry_entry.yaml
- tasks/composeobj_181__first_put_the_milk_in_the_basket_then_put_the_tomato_sauce_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_chocolate_pudding_in_th/registry_entry.yaml
- tasks/composeobj_182__first_put_the_milk_in_the_basket_then_put_the_tomato_sauce_in_the_basket_then_put_the_orange_juice_in_the_basket_and_finally_put_the_chocolate_pudding/registry_entry.yaml
- tasks/composeobj_183__first_put_the_milk_in_the_basket_then_put_the_butter_in_the_basket_then_put_the_orange_juice_in_the_basket_and_finally_put_the_chocolate_pudding_in_th/registry_entry.yaml
- tasks/composeobj_184__put_the_cream_cheese_box_in_the_basket_then_put_the_tomato_sauce_in_the_basket_and_finally_put_the_butter_in_the_basket/registry_entry.yaml
- tasks/composeobj_185__put_the_cream_cheese_box_in_the_basket_then_put_the_tomato_sauce_in_the_basket_and_finally_put_the_orange_juice_in_the_basket/registry_entry.yaml
- tasks/composeobj_186__put_the_cream_cheese_box_in_the_basket_then_put_the_tomato_sauce_in_the_basket_and_finally_put_the_chocolate_pudding_in_the_basket/registry_entry.yaml
- tasks/composeobj_187__put_the_cream_cheese_box_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_orange_juice_in_the_basket/registry_entry.yaml
- tasks/composeobj_188__put_the_cream_cheese_box_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_chocolate_pudding_in_the_basket/registry_entry.yaml
- tasks/composeobj_189__put_the_cream_cheese_box_in_the_basket_then_put_the_orange_juice_in_the_basket_and_finally_put_the_chocolate_pudding_in_the_basket/registry_entry.yaml
- tasks/composeobj_190__put_the_tomato_sauce_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_orange_juice_in_the_basket/registry_entry.yaml
- tasks/composeobj_191__put_the_tomato_sauce_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_chocolate_pudding_in_the_basket/registry_entry.yaml
- tasks/composeobj_192__put_the_tomato_sauce_in_the_basket_then_put_the_orange_juice_in_the_basket_and_finally_put_the_chocolate_pudding_in_the_basket/registry_entry.yaml
- tasks/composeobj_193__put_the_butter_in_the_basket_then_put_the_orange_juice_in_the_basket_and_finally_put_the_chocolate_pudding_in_the_basket/registry_entry.yaml
- tasks/composeobj_194__put_the_cream_cheese_box_in_the_basket_then_put_the_tomato_sauce_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_orange_juice_in_t/registry_entry.yaml
- tasks/composeobj_195__put_the_cream_cheese_box_in_the_basket_then_put_the_tomato_sauce_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_chocolate_pudding/registry_entry.yaml
- tasks/composeobj_196__put_the_cream_cheese_box_in_the_basket_then_put_the_tomato_sauce_in_the_basket_then_put_the_orange_juice_in_the_basket_and_finally_put_the_chocolate_p/registry_entry.yaml
- tasks/composeobj_197__put_the_cream_cheese_box_in_the_basket_then_put_the_butter_in_the_basket_then_put_the_orange_juice_in_the_basket_and_finally_put_the_chocolate_pudding/registry_entry.yaml
- tasks/composeobj_198__put_the_tomato_sauce_in_the_basket_then_put_the_butter_in_the_basket_then_put_the_orange_juice_in_the_basket_and_finally_put_the_chocolate_pudding_in/registry_entry.yaml
- tasks/composeobj_199__first_put_the_milk_in_the_basket_then_put_the_salad_dressing_in_the_basket_and_finally_put_the_ketchup_in_the_basket/registry_entry.yaml
- tasks/composeobj_200__first_put_the_milk_in_the_basket_then_put_the_salad_dressing_in_the_basket_and_finally_put_the_alphabet_soup_in_the_basket/registry_entry.yaml
- tasks/composeobj_201__first_put_the_milk_in_the_basket_then_put_the_salad_dressing_in_the_basket_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/composeobj_202__first_put_the_milk_in_the_basket_then_put_the_salad_dressing_in_the_basket_and_finally_put_the_tomato_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_203__first_put_the_milk_in_the_basket_then_put_the_ketchup_in_the_basket_and_finally_put_the_alphabet_soup_in_the_basket/registry_entry.yaml
- tasks/composeobj_204__first_put_the_milk_in_the_basket_then_put_the_ketchup_in_the_basket_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/composeobj_205__first_put_the_milk_in_the_basket_then_put_the_ketchup_in_the_basket_and_finally_put_the_tomato_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_206__first_put_the_milk_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/composeobj_207__first_put_the_milk_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_tomato_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_208__first_put_the_milk_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_tomato_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_209__first_put_the_milk_in_the_basket_then_put_the_salad_dressing_in_the_basket_then_put_the_ketchup_in_the_basket_and_finally_put_the_alphabet_soup_in_the/registry_entry.yaml
- tasks/composeobj_210__first_put_the_milk_in_the_basket_then_put_the_salad_dressing_in_the_basket_then_put_the_ketchup_in_the_basket_and_finally_put_the_cream_cheese_box_in/registry_entry.yaml
- tasks/composeobj_211__first_put_the_milk_in_the_basket_then_put_the_salad_dressing_in_the_basket_then_put_the_ketchup_in_the_basket_and_finally_put_the_tomato_sauce_in_the/registry_entry.yaml
- tasks/composeobj_212__first_put_the_milk_in_the_basket_then_put_the_salad_dressing_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_cream_cheese_b/registry_entry.yaml
- tasks/composeobj_213__first_put_the_milk_in_the_basket_then_put_the_salad_dressing_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_tomato_sauce_i/registry_entry.yaml
- tasks/composeobj_214__first_put_the_milk_in_the_basket_then_put_the_salad_dressing_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_tomato_sauc/registry_entry.yaml
- tasks/composeobj_215__first_put_the_milk_in_the_basket_then_put_the_ketchup_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_cream_cheese_box_in_t/registry_entry.yaml
- tasks/composeobj_216__first_put_the_milk_in_the_basket_then_put_the_ketchup_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_tomato_sauce_in_the_b/registry_entry.yaml
- tasks/composeobj_217__first_put_the_milk_in_the_basket_then_put_the_ketchup_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_tomato_sauce_in_th/registry_entry.yaml
- tasks/composeobj_218__first_put_the_milk_in_the_basket_then_put_the_alphabet_soup_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_tomato_sauce/registry_entry.yaml
- tasks/composeobj_219__put_the_salad_dressing_in_the_basket_then_put_the_ketchup_in_the_basket_and_finally_put_the_alphabet_soup_in_the_basket/registry_entry.yaml
- tasks/composeobj_220__put_the_salad_dressing_in_the_basket_then_put_the_ketchup_in_the_basket_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/composeobj_221__put_the_salad_dressing_in_the_basket_then_put_the_ketchup_in_the_basket_and_finally_put_the_tomato_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_222__put_the_salad_dressing_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/composeobj_223__put_the_salad_dressing_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_tomato_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_224__put_the_salad_dressing_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_tomato_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_225__put_the_ketchup_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/composeobj_226__put_the_ketchup_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_tomato_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_227__put_the_ketchup_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_tomato_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_228__put_the_alphabet_soup_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_tomato_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_229__put_the_salad_dressing_in_the_basket_then_put_the_ketchup_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_cream_cheese_box/registry_entry.yaml
- tasks/composeobj_230__put_the_salad_dressing_in_the_basket_then_put_the_ketchup_in_the_basket_then_put_the_alphabet_soup_in_the_basket_and_finally_put_the_tomato_sauce_in_t/registry_entry.yaml
- tasks/composeobj_231__put_the_salad_dressing_in_the_basket_then_put_the_ketchup_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_tomato_sauce_i/registry_entry.yaml
- tasks/composeobj_232__put_the_salad_dressing_in_the_basket_then_put_the_alphabet_soup_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_tomato_s/registry_entry.yaml
- tasks/composeobj_233__put_the_ketchup_in_the_basket_then_put_the_alphabet_soup_in_the_basket_then_put_the_cream_cheese_box_in_the_basket_and_finally_put_the_tomato_sauce_in/registry_entry.yaml
- tasks/composeobj_234__first_put_the_milk_in_the_basket_then_put_the_tomato_sauce_in_the_basket_and_finally_put_the_butter_in_the_basket/registry_entry.yaml
- tasks/composeobj_235__first_put_the_milk_in_the_basket_then_put_the_tomato_sauce_in_the_basket_and_finally_put_the_orange_juice_in_the_basket/registry_entry.yaml
- tasks/composeobj_236__first_put_the_milk_in_the_basket_then_put_the_tomato_sauce_in_the_basket_and_finally_put_the_chocolate_pudding_in_the_basket/registry_entry.yaml
- tasks/composeobj_237__first_put_the_milk_in_the_basket_then_put_the_tomato_sauce_in_the_basket_and_finally_put_the_bbq_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_238__first_put_the_milk_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_orange_juice_in_the_basket/registry_entry.yaml
- tasks/composeobj_239__first_put_the_milk_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_chocolate_pudding_in_the_basket/registry_entry.yaml
- tasks/composeobj_240__first_put_the_milk_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_bbq_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_241__first_put_the_milk_in_the_basket_then_put_the_orange_juice_in_the_basket_and_finally_put_the_chocolate_pudding_in_the_basket/registry_entry.yaml
- tasks/composeobj_242__first_put_the_milk_in_the_basket_then_put_the_orange_juice_in_the_basket_and_finally_put_the_bbq_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_243__first_put_the_milk_in_the_basket_then_put_the_chocolate_pudding_in_the_basket_and_finally_put_the_bbq_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_244__first_put_the_milk_in_the_basket_then_put_the_tomato_sauce_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_orange_juice_in_the_bas/registry_entry.yaml
- tasks/composeobj_245__first_put_the_milk_in_the_basket_then_put_the_tomato_sauce_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_chocolate_pudding_in_th/registry_entry.yaml
- tasks/composeobj_246__first_put_the_milk_in_the_basket_then_put_the_tomato_sauce_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_bbq_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_247__first_put_the_milk_in_the_basket_then_put_the_tomato_sauce_in_the_basket_then_put_the_orange_juice_in_the_basket_and_finally_put_the_chocolate_pudding/registry_entry.yaml
- tasks/composeobj_248__first_put_the_milk_in_the_basket_then_put_the_tomato_sauce_in_the_basket_then_put_the_orange_juice_in_the_basket_and_finally_put_the_bbq_sauce_in_the/registry_entry.yaml
- tasks/composeobj_249__first_put_the_milk_in_the_basket_then_put_the_tomato_sauce_in_the_basket_then_put_the_chocolate_pudding_in_the_basket_and_finally_put_the_bbq_sauce_in/registry_entry.yaml
- tasks/composeobj_250__first_put_the_milk_in_the_basket_then_put_the_butter_in_the_basket_then_put_the_orange_juice_in_the_basket_and_finally_put_the_chocolate_pudding_in_th/registry_entry.yaml
- tasks/composeobj_251__first_put_the_milk_in_the_basket_then_put_the_butter_in_the_basket_then_put_the_orange_juice_in_the_basket_and_finally_put_the_bbq_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_252__first_put_the_milk_in_the_basket_then_put_the_butter_in_the_basket_then_put_the_chocolate_pudding_in_the_basket_and_finally_put_the_bbq_sauce_in_the_b/registry_entry.yaml
- tasks/composeobj_253__first_put_the_milk_in_the_basket_then_put_the_orange_juice_in_the_basket_then_put_the_chocolate_pudding_in_the_basket_and_finally_put_the_bbq_sauce_in/registry_entry.yaml
- tasks/composeobj_254__put_the_tomato_sauce_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_orange_juice_in_the_basket/registry_entry.yaml
- tasks/composeobj_255__put_the_tomato_sauce_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_chocolate_pudding_in_the_basket/registry_entry.yaml
- tasks/composeobj_256__put_the_tomato_sauce_in_the_basket_then_put_the_butter_in_the_basket_and_finally_put_the_bbq_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_257__put_the_tomato_sauce_in_the_basket_then_put_the_orange_juice_in_the_basket_and_finally_put_the_chocolate_pudding_in_the_basket/registry_entry.yaml
- tasks/composeobj_258__put_the_tomato_sauce_in_the_basket_then_put_the_orange_juice_in_the_basket_and_finally_put_the_bbq_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_259__put_the_tomato_sauce_in_the_basket_then_put_the_chocolate_pudding_in_the_basket_and_finally_put_the_bbq_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_260__put_the_butter_in_the_basket_then_put_the_orange_juice_in_the_basket_and_finally_put_the_chocolate_pudding_in_the_basket/registry_entry.yaml
- tasks/composeobj_261__put_the_butter_in_the_basket_then_put_the_orange_juice_in_the_basket_and_finally_put_the_bbq_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_262__put_the_butter_in_the_basket_then_put_the_chocolate_pudding_in_the_basket_and_finally_put_the_bbq_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_263__put_the_orange_juice_in_the_basket_then_put_the_chocolate_pudding_in_the_basket_and_finally_put_the_bbq_sauce_in_the_basket/registry_entry.yaml
- tasks/composeobj_264__put_the_tomato_sauce_in_the_basket_then_put_the_butter_in_the_basket_then_put_the_orange_juice_in_the_basket_and_finally_put_the_chocolate_pudding_in/registry_entry.yaml
- tasks/composeobj_265__put_the_tomato_sauce_in_the_basket_then_put_the_butter_in_the_basket_then_put_the_orange_juice_in_the_basket_and_finally_put_the_bbq_sauce_in_the_bask/registry_entry.yaml
- tasks/composeobj_266__put_the_tomato_sauce_in_the_basket_then_put_the_butter_in_the_basket_then_put_the_chocolate_pudding_in_the_basket_and_finally_put_the_bbq_sauce_in_the/registry_entry.yaml
- tasks/composeobj_267__put_the_tomato_sauce_in_the_basket_then_put_the_orange_juice_in_the_basket_then_put_the_chocolate_pudding_in_the_basket_and_finally_put_the_bbq_sauce/registry_entry.yaml
- tasks/composeobj_268__put_the_butter_in_the_basket_then_put_the_orange_juice_in_the_basket_then_put_the_chocolate_pudding_in_the_basket_and_finally_put_the_bbq_sauce_in_the/registry_entry.yaml
