registry_entries:
- tasks/compose_001__put_the_alphabet_soup_the_salad_dressing_the_cream_cheese_box_and_the_milk_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_002__put_the_alphabet_soup_the_salad_dressing_the_cream_cheese_box_and_the_tomato_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_003__put_the_alphabet_soup_the_salad_dressing_the_cream_cheese_box_and_the_butter_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_004__put_the_alphabet_soup_the_salad_dressing_the_milk_and_the_tomato_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_005__put_the_alphabet_soup_the_salad_dressing_the_milk_and_the_butter_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_006__put_the_alphabet_soup_the_salad_dressing_the_tomato_sauce_and_the_butter_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_007__put_the_alphabet_soup_the_cream_cheese_box_the_milk_and_the_tomato_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_008__put_the_alphabet_soup_the_cream_cheese_box_the_milk_and_the_butter_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_009__put_the_alphabet_soup_the_cream_cheese_box_the_tomato_sauce_and_the_butter_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_010__put_the_alphabet_soup_the_milk_the_tomato_sauce_and_the_butter_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_011__put_the_salad_dressing_the_cream_cheese_box_the_milk_and_the_tomato_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_012__put_the_salad_dressing_the_cream_cheese_box_the_milk_and_the_butter_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_013__put_the_salad_dressing_the_cream_cheese_box_the_tomato_sauce_and_the_butter_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_014__put_the_salad_dressing_the_milk_the_tomato_sauce_and_the_butter_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_015__put_the_cream_cheese_box_the_milk_the_tomato_sauce_and_the_butter_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_016__put_the_bbq_sauce_the_chocolate_pudding_the_ketchup_and_the_salad_dressing_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_017__put_the_bbq_sauce_the_chocolate_pudding_the_ketchup_and_the_alphabet_soup_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_018__put_the_bbq_sauce_the_chocolate_pudding_the_ketchup_and_the_cream_cheese_box_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_019__put_the_bbq_sauce_the_chocolate_pudding_the_salad_dressing_and_the_alphabet_soup_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_020__put_the_bbq_sauce_the_chocolate_pudding_the_salad_dressing_and_the_cream_cheese_box_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_021__put_the_bbq_sauce_the_chocolate_pudding_the_alphabet_soup_and_the_cream_cheese_box_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_022__put_the_bbq_sauce_the_ketchup_the_salad_dressing_and_the_alphabet_soup_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_023__put_the_bbq_sauce_the_ketchup_the_salad_dressing_and_the_cream_cheese_box_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_024__put_the_bbq_sauce_the_ketchup_the_alphabet_soup_and_the_cream_cheese_box_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_025__put_the_bbq_sauce_the_salad_dressing_the_alphabet_soup_and_the_cream_cheese_box_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_026__put_the_chocolate_pudding_the_ketchup_the_salad_dressing_and_the_alphabet_soup_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_027__put_the_chocolate_pudding_the_ketchup_the_salad_dressing_and_the_cream_cheese_box_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_028__put_the_chocolate_pudding_the_ketchup_the_alphabet_soup_and_the_cream_cheese_box_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_029__put_the_chocolate_pudding_the_salad_dressing_the_alphabet_soup_and_the_cream_cheese_box_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_030__put_the_ketchup_the_salad_dressing_the_alphabet_soup_and_the_cream_cheese_box_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_031__put_the_butter_the_tomato_sauce_the_orange_juice_and_the_chocolate_pudding_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_032__put_the_butter_the_tomato_sauce_the_orange_juice_and_the_bbq_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_033__put_the_butter_the_tomato_sauce_the_orange_juice_and_the_ketchup_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_034__put_the_butter_the_tomato_sauce_the_chocolate_pudding_and_the_bbq_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_035__put_the_butter_the_tomato_sauce_the_chocolate_pudding_and_the_ketchup_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_036__put_the_butter_the_tomato_sauce_the_bbq_sauce_and_the_ketchup_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_037__put_the_butter_the_orange_juice_the_chocolate_pudding_and_the_bbq_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_038__put_the_butter_the_orange_juice_the_chocolate_pudding_and_the_ketchup_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_039__put_the_butter_the_orange_juice_the_bbq_sauce_and_the_ketchup_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_040__put_the_butter_the_chocolate_pudding_the_bbq_sauce_and_the_ketchup_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_041__put_the_tomato_sauce_the_orange_juice_the_chocolate_pudding_and_the_bbq_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_042__put_the_tomato_sauce_the_orange_juice_the_chocolate_pudding_and_the_ketchup_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_043__put_the_tomato_sauce_the_orange_juice_the_bbq_sauce_and_the_ketchup_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_044__put_the_tomato_sauce_the_chocolate_pudding_the_bbq_sauce_and_the_ketchup_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_045__put_the_orange_juice_the_chocolate_pudding_the_bbq_sauce_and_the_ketchup_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_046__put_the_chocolate_pudding_the_orange_juice_the_bbq_sauce_and_the_ketchup_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_047__put_the_chocolate_pudding_the_orange_juice_the_bbq_sauce_and_the_salad_dressing_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_048__put_the_chocolate_pudding_the_orange_juice_the_bbq_sauce_and_the_alphabet_soup_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_049__put_the_chocolate_pudding_the_orange_juice_the_ketchup_and_the_salad_dressing_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_050__put_the_chocolate_pudding_the_orange_juice_the_ketchup_and_the_alphabet_soup_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_051__put_the_chocolate_pudding_the_orange_juice_the_salad_dressing_and_the_alphabet_soup_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_052__put_the_chocolate_pudding_the_bbq_sauce_the_ketchup_and_the_salad_dressing_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_053__put_the_chocolate_pudding_the_bbq_sauce_the_ketchup_and_the_alphabet_soup_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_054__put_the_chocolate_pudding_the_bbq_sauce_the_salad_dressing_and_the_alphabet_soup_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_055__put_the_chocolate_pudding_the_ketchup_the_salad_dressing_and_the_alphabet_soup_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_056__put_the_orange_juice_the_bbq_sauce_the_ketchup_and_the_salad_dressing_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_057__put_the_orange_juice_the_bbq_sauce_the_ketchup_and_the_alphabet_soup_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_058__put_the_orange_juice_the_bbq_sauce_the_salad_dressing_and_the_alphabet_soup_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_059__put_the_orange_juice_the_ketchup_the_salad_dressing_and_the_alphabet_soup_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_060__put_the_bbq_sauce_the_ketchup_the_salad_dressing_and_the_alphabet_soup_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_061__put_the_cream_cheese_box_the_alphabet_soup_the_milk_and_the_tomato_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_062__put_the_cream_cheese_box_the_alphabet_soup_the_milk_and_the_butter_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_063__put_the_cream_cheese_box_the_alphabet_soup_the_milk_and_the_orange_juice_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_064__put_the_cream_cheese_box_the_alphabet_soup_the_tomato_sauce_and_the_butter_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_065__put_the_cream_cheese_box_the_alphabet_soup_the_tomato_sauce_and_the_orange_juice_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_066__put_the_cream_cheese_box_the_alphabet_soup_the_butter_and_the_orange_juice_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_067__put_the_cream_cheese_box_the_milk_the_tomato_sauce_and_the_butter_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_068__put_the_cream_cheese_box_the_milk_the_tomato_sauce_and_the_orange_juice_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_069__put_the_cream_cheese_box_the_milk_the_butter_and_the_orange_juice_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_070__put_the_cream_cheese_box_the_tomato_sauce_the_butter_and_the_orange_juice_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_071__put_the_alphabet_soup_the_milk_the_tomato_sauce_and_the_butter_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_072__put_the_alphabet_soup_the_milk_the_tomato_sauce_and_the_orange_juice_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_073__put_the_alphabet_soup_the_milk_the_butter_and_the_orange_juice_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_074__put_the_alphabet_soup_the_tomato_sauce_the_butter_and_the_orange_juice_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_075__put_the_milk_the_tomato_sauce_the_butter_and_the_orange_juice_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_076__put_the_ketchup_the_bbq_sauce_the_salad_dressing_and_the_alphabet_soup_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_077__put_the_ketchup_the_bbq_sauce_the_salad_dressing_and_the_cream_cheese_box_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_078__put_the_ketchup_the_bbq_sauce_the_salad_dressing_and_the_milk_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_079__put_the_ketchup_the_bbq_sauce_the_alphabet_soup_and_the_cream_cheese_box_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_080__put_the_ketchup_the_bbq_sauce_the_alphabet_soup_and_the_milk_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_081__put_the_ketchup_the_bbq_sauce_the_cream_cheese_box_and_the_milk_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_082__put_the_ketchup_the_salad_dressing_the_alphabet_soup_and_the_cream_cheese_box_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_083__put_the_ketchup_the_salad_dressing_the_alphabet_soup_and_the_milk_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_084__put_the_ketchup_the_salad_dressing_the_cream_cheese_box_and_the_milk_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_085__put_the_ketchup_the_alphabet_soup_the_cream_cheese_box_and_the_milk_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_086__put_the_bbq_sauce_the_salad_dressing_the_alphabet_soup_and_the_cream_cheese_box_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_087__put_the_bbq_sauce_the_salad_dressing_the_alphabet_soup_and_the_milk_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_088__put_the_bbq_sauce_the_salad_dressing_the_cream_cheese_box_and_the_milk_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_089__put_the_bbq_sauce_the_alphabet_soup_the_cream_cheese_box_and_the_milk_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_090__put_the_salad_dressing_the_alphabet_soup_the_cream_cheese_box_and_the_milk_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_091__put_the_milk_the_cream_cheese_box_the_tomato_sauce_and_the_butter_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_092__put_the_milk_the_cream_cheese_box_the_tomato_sauce_and_the_orange_juice_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_093__put_the_milk_the_cream_cheese_box_the_tomato_sauce_and_the_chocolate_pudding_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_094__put_the_milk_the_cream_cheese_box_the_butter_and_the_orange_juice_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_095__put_the_milk_the_cream_cheese_box_the_butter_and_the_chocolate_pudding_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_096__put_the_milk_the_cream_cheese_box_the_orange_juice_and_the_chocolate_pudding_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_097__put_the_milk_the_tomato_sauce_the_butter_and_the_orange_juice_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_098__put_the_milk_the_tomato_sauce_the_butter_and_the_chocolate_pudding_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_099__put_the_milk_the_tomato_sauce_the_orange_juice_and_the_chocolate_pudding_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_100__put_the_milk_the_butter_the_orange_juice_and_the_chocolate_pudding_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_101__put_the_cream_cheese_box_the_tomato_sauce_the_butter_and_the_orange_juice_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_102__put_the_cream_cheese_box_the_tomato_sauce_the_butter_and_the_chocolate_pudding_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_103__put_the_cream_cheese_box_the_tomato_sauce_the_orange_juice_and_the_chocolate_pudding_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_104__put_the_cream_cheese_box_the_butter_the_orange_juice_and_the_chocolate_pudding_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_105__put_the_tomato_sauce_the_butter_the_orange_juice_and_the_chocolate_pudding_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_106__put_the_orange_juice_the_butter_the_chocolate_pudding_and_the_bbq_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_107__put_the_orange_juice_the_butter_the_chocolate_pudding_and_the_ketchup_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_108__put_the_orange_juice_the_butter_the_chocolate_pudding_and_the_salad_dressing_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_109__put_the_orange_juice_the_butter_the_bbq_sauce_and_the_ketchup_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_110__put_the_orange_juice_the_butter_the_bbq_sauce_and_the_salad_dressing_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_111__put_the_orange_juice_the_butter_the_ketchup_and_the_salad_dressing_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_112__put_the_orange_juice_the_chocolate_pudding_the_bbq_sauce_and_the_ketchup_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_113__put_the_orange_juice_the_chocolate_pudding_the_bbq_sauce_and_the_salad_dressing_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_114__put_the_orange_juice_the_chocolate_pudding_the_ketchup_and_the_salad_dressing_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_115__put_the_orange_juice_the_bbq_sauce_the_ketchup_and_the_salad_dressing_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_116__put_the_butter_the_chocolate_pudding_the_bbq_sauce_and_the_ketchup_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_117__put_the_butter_the_chocolate_pudding_the_bbq_sauce_and_the_salad_dressing_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_118__put_the_butter_the_chocolate_pudding_the_ketchup_and_the_salad_dressing_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_119__put_the_butter_the_bbq_sauce_the_ketchup_and_the_salad_dressing_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_120__put_the_chocolate_pudding_the_bbq_sauce_the_ketchup_and_the_salad_dressing_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_121__put_the_salad_dressing_the_ketchup_the_alphabet_soup_and_the_cream_cheese_box_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_122__put_the_salad_dressing_the_ketchup_the_alphabet_soup_and_the_milk_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_123__put_the_salad_dressing_the_ketchup_the_alphabet_soup_and_the_tomato_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_124__put_the_salad_dressing_the_ketchup_the_cream_cheese_box_and_the_milk_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_125__put_the_salad_dressing_the_ketchup_the_cream_cheese_box_and_the_tomato_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_126__put_the_salad_dressing_the_ketchup_the_milk_and_the_tomato_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_127__put_the_salad_dressing_the_alphabet_soup_the_cream_cheese_box_and_the_milk_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_128__put_the_salad_dressing_the_alphabet_soup_the_cream_cheese_box_and_the_tomato_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_129__put_the_salad_dressing_the_alphabet_soup_the_milk_and_the_tomato_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_130__put_the_salad_dressing_the_cream_cheese_box_the_milk_and_the_tomato_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_131__put_the_ketchup_the_alphabet_soup_the_cream_cheese_box_and_the_milk_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_132__put_the_ketchup_the_alphabet_soup_the_cream_cheese_box_and_the_tomato_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_133__put_the_ketchup_the_alphabet_soup_the_milk_and_the_tomato_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_134__put_the_ketchup_the_cream_cheese_box_the_milk_and_the_tomato_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_135__put_the_alphabet_soup_the_cream_cheese_box_the_milk_and_the_tomato_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_136__put_the_tomato_sauce_the_milk_the_butter_and_the_orange_juice_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_137__put_the_tomato_sauce_the_milk_the_butter_and_the_chocolate_pudding_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_138__put_the_tomato_sauce_the_milk_the_butter_and_the_bbq_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_139__put_the_tomato_sauce_the_milk_the_orange_juice_and_the_chocolate_pudding_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_140__put_the_tomato_sauce_the_milk_the_orange_juice_and_the_bbq_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_141__put_the_tomato_sauce_the_milk_the_chocolate_pudding_and_the_bbq_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_142__put_the_tomato_sauce_the_butter_the_orange_juice_and_the_chocolate_pudding_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_143__put_the_tomato_sauce_the_butter_the_orange_juice_and_the_bbq_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_144__put_the_tomato_sauce_the_butter_the_chocolate_pudding_and_the_bbq_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_145__put_the_tomato_sauce_the_orange_juice_the_chocolate_pudding_and_the_bbq_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_146__put_the_milk_the_butter_the_orange_juice_and_the_chocolate_pudding_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_147__put_the_milk_the_butter_the_orange_juice_and_the_bbq_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_148__put_the_milk_the_butter_the_chocolate_pudding_and_the_bbq_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_149__put_the_milk_the_orange_juice_the_chocolate_pudding_and_the_bbq_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_150__put_the_butter_the_orange_juice_the_chocolate_pudding_and_the_bbq_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_151__put_the_alphabet_soup_the_cream_cheese_box_the_ketchup_and_the_tomato_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_152__put_the_alphabet_soup_the_butter_and_the_cream_cheese_box_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_153__put_the_alphabet_soup_the_butter_and_the_ketchup_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_154__put_the_alphabet_soup_the_butter_and_the_orange_juice_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_155__put_the_alphabet_soup_the_butter_and_the_tomato_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_156__put_the_alphabet_soup_the_cream_cheese_box_and_the_ketchup_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_157__put_the_alphabet_soup_the_cream_cheese_box_and_the_orange_juice_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_158__put_the_alphabet_soup_the_cream_cheese_box_and_the_tomato_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_159__put_the_alphabet_soup_the_ketchup_and_the_orange_juice_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_160__put_the_alphabet_soup_the_ketchup_and_the_tomato_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_161__put_the_alphabet_soup_the_orange_juice_and_the_tomato_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_162__put_the_butter_the_cream_cheese_box_and_the_ketchup_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_163__put_the_butter_the_cream_cheese_box_and_the_orange_juice_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_164__put_the_butter_the_cream_cheese_box_and_the_tomato_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_165__put_the_butter_the_ketchup_and_the_orange_juice_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_166__put_the_butter_the_ketchup_and_the_tomato_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_167__put_the_butter_the_orange_juice_and_the_tomato_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_168__put_the_cream_cheese_box_the_ketchup_and_the_orange_juice_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_169__put_the_cream_cheese_box_the_ketchup_and_the_tomato_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_170__put_the_cream_cheese_box_the_orange_juice_and_the_tomato_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_171__put_the_ketchup_the_orange_juice_and_the_tomato_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_172__put_the_alphabet_soup_the_butter_the_cream_cheese_box_and_the_ketchup_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_173__put_the_alphabet_soup_the_butter_the_cream_cheese_box_and_the_orange_juice_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_174__put_the_alphabet_soup_the_butter_the_cream_cheese_box_and_the_tomato_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_175__put_the_alphabet_soup_the_butter_the_ketchup_and_the_orange_juice_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_176__put_the_alphabet_soup_the_butter_the_ketchup_and_the_tomato_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_177__put_the_alphabet_soup_the_butter_the_orange_juice_and_the_tomato_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_178__put_the_alphabet_soup_the_cream_cheese_box_the_ketchup_and_the_orange_juice_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_179__put_the_alphabet_soup_the_cream_cheese_box_the_ketchup_and_the_tomato_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_180__put_the_alphabet_soup_the_cream_cheese_box_the_orange_juice_and_the_tomato_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_181__put_the_alphabet_soup_the_ketchup_the_orange_juice_and_the_tomato_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_182__put_the_butter_the_cream_cheese_box_the_ketchup_and_the_orange_juice_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_183__put_the_butter_the_cream_cheese_box_the_ketchup_and_the_tomato_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_184__put_the_butter_the_cream_cheese_box_the_orange_juice_and_the_tomato_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_185__put_the_butter_the_ketchup_the_orange_juice_and_the_tomato_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_186__put_the_cream_cheese_box_the_ketchup_the_orange_juice_and_the_tomato_sauce_in_the_basket_one_after_another/registry_entry.yaml
- tasks/compose_187__put_the_cream_cheese_on_the_black_bowl_then_put_the_black_bowl_on_the_plate_then_put_the_wine_bottle_on_the_rack_and_finally_push_the_plate_to_the_fro/registry_entry.yaml
- tasks/compose_188__put_the_cream_cheese_on_the_black_bowl_then_put_the_black_bowl_on_the_plate_then_put_the_wine_bottle_on_the_rack_and_finally_turn_on_the_stove/registry_entry.yaml
- tasks/compose_189__put_the_cream_cheese_on_the_black_bowl_then_put_the_black_bowl_on_the_plate_then_put_the_wine_bottle_on_the_rack_and_finally_open_the_middle_drawer_of/registry_entry.yaml
- tasks/compose_190__put_the_black_bowl_on_the_plate_then_put_the_wine_bottle_on_the_rack_then_push_the_plate_to_the_front_of_the_stove_and_finally_turn_on_the_stove/registry_entry.yaml
- tasks/compose_191__put_the_black_bowl_on_the_plate_then_put_the_wine_bottle_on_the_rack_then_push_the_plate_to_the_front_of_the_stove_and_finally_open_the_middle_drawer/registry_entry.yaml
- tasks/compose_192__put_the_black_bowl_on_the_plate_then_put_the_wine_bottle_on_the_rack_then_turn_on_the_stove_and_finally_open_the_middle_drawer_of_the_cabinet/registry_entry.yaml
- tasks/compose_193__put_the_cream_cheese_on_the_black_bowl_then_put_the_black_bowl_on_the_plate_then_put_the_wine_bottle_on_top_of_the_cabinet_and_finally_push_the_plate/registry_entry.yaml
- tasks/compose_194__put_the_cream_cheese_on_the_black_bowl_then_put_the_black_bowl_on_the_plate_then_put_the_wine_bottle_on_top_of_the_cabinet_and_finally_turn_on_the_sto/registry_entry.yaml
- tasks/compose_195__put_the_cream_cheese_on_the_black_bowl_then_put_the_black_bowl_on_the_plate_then_put_the_wine_bottle_on_top_of_the_cabinet_and_finally_open_the_middle/registry_entry.yaml
- tasks/compose_196__put_the_cream_cheese_on_the_black_bowl_then_put_the_black_bowl_on_the_plate_then_push_the_plate_to_the_front_of_the_stove_and_finally_turn_on_the_stov/registry_entry.yaml
- tasks/compose_197__put_the_cream_cheese_on_the_black_bowl_then_put_the_black_bowl_on_the_plate_then_push_the_plate_to_the_front_of_the_stove_and_finally_open_the_middle/registry_entry.yaml
- tasks/compose_198__put_the_cream_cheese_on_the_black_bowl_then_put_the_black_bowl_on_the_plate_then_turn_on_the_stove_and_finally_open_the_middle_drawer_of_the_cabinet/registry_entry.yaml
- tasks/compose_199__put_the_black_bowl_on_the_plate_then_put_the_wine_bottle_on_top_of_the_cabinet_then_push_the_plate_to_the_front_of_the_stove_and_finally_turn_on_the_s/registry_entry.yaml
- tasks/compose_200__put_the_black_bowl_on_the_plate_then_put_the_wine_bottle_on_top_of_the_cabinet_then_push_the_plate_to_the_front_of_the_stove_and_finally_open_the_midd/registry_entry.yaml
- tasks/compose_201__put_the_black_bowl_on_the_plate_then_put_the_wine_bottle_on_top_of_the_cabinet_then_turn_on_the_stove_and_finally_open_the_middle_drawer_of_the_cabine/registry_entry.yaml
- tasks/compose_202__put_the_black_bowl_on_the_plate_then_push_the_plate_to_the_front_of_the_stove_then_turn_on_the_stove_and_finally_open_the_middle_drawer_of_the_cabinet/registry_entry.yaml
- tasks/compose_203__put_the_cream_cheese_on_the_black_bowl_then_put_the_wine_bottle_on_the_rack_then_push_the_plate_to_the_front_of_the_stove_and_finally_open_the_top_dra/registry_entry.yaml
- tasks/compose_204__put_the_cream_cheese_on_the_black_bowl_then_put_the_wine_bottle_on_the_rack_then_turn_on_the_stove_and_finally_open_the_top_drawer_and_put_the_black_b/registry_entry.yaml
- tasks/compose_205__put_the_cream_cheese_on_the_black_bowl_then_put_the_wine_bottle_on_the_rack_then_open_the_middle_drawer_of_the_cabinet_and_finally_open_the_top_drawer/registry_entry.yaml
- tasks/compose_206__put_the_wine_bottle_on_the_rack_then_push_the_plate_to_the_front_of_the_stove_then_turn_on_the_stove_and_finally_open_the_top_drawer_and_put_the_black/registry_entry.yaml
- tasks/compose_207__put_the_wine_bottle_on_the_rack_then_push_the_plate_to_the_front_of_the_stove_then_open_the_middle_drawer_of_the_cabinet_and_finally_open_the_top_draw/registry_entry.yaml
- tasks/compose_208__put_the_wine_bottle_on_the_rack_then_turn_on_the_stove_then_open_the_middle_drawer_of_the_cabinet_and_finally_open_the_top_drawer_and_put_the_black_bo/registry_entry.yaml
- tasks/compose_209__put_the_cream_cheese_on_the_black_bowl_then_put_the_wine_bottle_on_the_rack_then_push_the_plate_to_the_front_of_the_stove_and_finally_turn_on_the_stov/registry_entry.yaml
- tasks/compose_210__put_the_cream_cheese_on_the_black_bowl_then_put_the_wine_bottle_on_the_rack_then_push_the_plate_to_the_front_of_the_stove_and_finally_put_the_black_bo/registry_entry.yaml
- tasks/compose_211__put_the_cream_cheese_on_the_black_bowl_then_put_the_wine_bottle_on_the_rack_then_push_the_plate_to_the_front_of_the_stove_and_finally_put_the_black_bo/registry_entry.yaml
- tasks/compose_212__put_the_cream_cheese_on_the_black_bowl_then_put_the_wine_bottle_on_the_rack_then_push_the_plate_to_the_front_of_the_stove_and_finally_open_the_middle/registry_entry.yaml
- tasks/compose_213__put_the_cream_cheese_on_the_black_bowl_then_put_the_wine_bottle_on_the_rack_then_turn_on_the_stove_and_finally_put_the_black_bowl_on_the_stove/registry_entry.yaml
- tasks/compose_214__put_the_cream_cheese_on_the_black_bowl_then_put_the_wine_bottle_on_the_rack_then_turn_on_the_stove_and_finally_put_the_black_bowl_on_top_of_the_cabine/registry_entry.yaml
- tasks/compose_215__put_the_cream_cheese_on_the_black_bowl_then_put_the_wine_bottle_on_the_rack_then_turn_on_the_stove_and_finally_open_the_middle_drawer_of_the_cabinet/registry_entry.yaml
- tasks/compose_216__put_the_cream_cheese_on_the_black_bowl_then_put_the_wine_bottle_on_the_rack_then_open_the_middle_drawer_of_the_cabinet_and_finally_put_the_black_bowl/registry_entry.yaml
- tasks/compose_217__put_the_cream_cheese_on_the_black_bowl_then_put_the_wine_bottle_on_the_rack_then_open_the_middle_drawer_of_the_cabinet_and_finally_put_the_black_bowl/registry_entry.yaml
- tasks/compose_218__put_the_wine_bottle_on_the_rack_then_push_the_plate_to_the_front_of_the_stove_then_turn_on_the_stove_and_finally_put_the_black_bowl_on_the_stove/registry_entry.yaml
- tasks/compose_219__put_the_wine_bottle_on_the_rack_then_push_the_plate_to_the_front_of_the_stove_then_turn_on_the_stove_and_finally_put_the_black_bowl_on_top_of_the_cabi/registry_entry.yaml
- tasks/compose_220__put_the_wine_bottle_on_the_rack_then_push_the_plate_to_the_front_of_the_stove_then_turn_on_the_stove_and_finally_open_the_middle_drawer_of_the_cabinet/registry_entry.yaml
- tasks/compose_221__put_the_wine_bottle_on_the_rack_then_push_the_plate_to_the_front_of_the_stove_then_open_the_middle_drawer_of_the_cabinet_and_finally_put_the_black_bow/registry_entry.yaml
- tasks/compose_222__put_the_wine_bottle_on_the_rack_then_push_the_plate_to_the_front_of_the_stove_then_open_the_middle_drawer_of_the_cabinet_and_finally_put_the_black_bow/registry_entry.yaml
- tasks/compose_223__put_the_wine_bottle_on_the_rack_then_turn_on_the_stove_then_open_the_middle_drawer_of_the_cabinet_and_finally_put_the_black_bowl_on_the_stove/registry_entry.yaml
- tasks/compose_224__put_the_wine_bottle_on_the_rack_then_turn_on_the_stove_then_open_the_middle_drawer_of_the_cabinet_and_finally_put_the_black_bowl_on_top_of_the_cabinet/registry_entry.yaml
- tasks/compose_225__put_the_cream_cheese_on_the_black_bowl_then_put_the_wine_bottle_on_top_of_the_cabinet_then_push_the_plate_to_the_front_of_the_stove_and_finally_open_t/registry_entry.yaml
- tasks/compose_226__put_the_cream_cheese_on_the_black_bowl_then_put_the_wine_bottle_on_top_of_the_cabinet_then_turn_on_the_stove_and_finally_open_the_top_drawer_and_put_t/registry_entry.yaml
- tasks/compose_227__put_the_cream_cheese_on_the_black_bowl_then_put_the_wine_bottle_on_top_of_the_cabinet_then_open_the_middle_drawer_of_the_cabinet_and_finally_open_the/registry_entry.yaml
- tasks/compose_228__put_the_cream_cheese_on_the_black_bowl_then_push_the_plate_to_the_front_of_the_stove_then_turn_on_the_stove_and_finally_open_the_top_drawer_and_put_th/registry_entry.yaml
- tasks/compose_229__put_the_cream_cheese_on_the_black_bowl_then_push_the_plate_to_the_front_of_the_stove_then_open_the_middle_drawer_of_the_cabinet_and_finally_open_the_t/registry_entry.yaml
- tasks/compose_230__put_the_cream_cheese_on_the_black_bowl_then_turn_on_the_stove_then_open_the_middle_drawer_of_the_cabinet_and_finally_open_the_top_drawer_and_put_the_b/registry_entry.yaml
- tasks/compose_231__put_the_wine_bottle_on_top_of_the_cabinet_then_push_the_plate_to_the_front_of_the_stove_then_turn_on_the_stove_and_finally_open_the_top_drawer_and_put/registry_entry.yaml
- tasks/compose_232__put_the_wine_bottle_on_top_of_the_cabinet_then_push_the_plate_to_the_front_of_the_stove_then_open_the_middle_drawer_of_the_cabinet_and_finally_open_th/registry_entry.yaml
- tasks/compose_233__put_the_wine_bottle_on_top_of_the_cabinet_then_turn_on_the_stove_then_open_the_middle_drawer_of_the_cabinet_and_finally_open_the_top_drawer_and_put_th/registry_entry.yaml
- tasks/compose_234__push_the_plate_to_the_front_of_the_stove_then_turn_on_the_stove_then_open_the_middle_drawer_of_the_cabinet_and_finally_open_the_top_drawer_and_put_the/registry_entry.yaml
- tasks/compose_235__put_the_cream_cheese_on_the_black_bowl_then_put_the_wine_bottle_on_top_of_the_cabinet_then_push_the_plate_to_the_front_of_the_stove_and_finally_turn_o/registry_entry.yaml
- tasks/compose_236__put_the_cream_cheese_on_the_black_bowl_then_put_the_wine_bottle_on_top_of_the_cabinet_then_push_the_plate_to_the_front_of_the_stove_and_finally_put_th/registry_entry.yaml
- tasks/compose_237__put_the_cream_cheese_on_the_black_bowl_then_put_the_wine_bottle_on_top_of_the_cabinet_then_push_the_plate_to_the_front_of_the_stove_and_finally_open_t/registry_entry.yaml
- tasks/compose_238__put_the_cream_cheese_on_the_black_bowl_then_put_the_wine_bottle_on_top_of_the_cabinet_then_turn_on_the_stove_and_finally_put_the_black_bowl_on_the_sto/registry_entry.yaml
- tasks/compose_239__put_the_cream_cheese_on_the_black_bowl_then_put_the_wine_bottle_on_top_of_the_cabinet_then_turn_on_the_stove_and_finally_open_the_middle_drawer_of_the/registry_entry.yaml
- tasks/compose_240__put_the_cream_cheese_on_the_black_bowl_then_put_the_wine_bottle_on_top_of_the_cabinet_then_open_the_middle_drawer_of_the_cabinet_and_finally_put_the_b/registry_entry.yaml
- tasks/compose_241__put_the_cream_cheese_on_the_black_bowl_then_push_the_plate_to_the_front_of_the_stove_then_turn_on_the_stove_and_finally_put_the_black_bowl_on_the_stov/registry_entry.yaml
- tasks/compose_242__put_the_cream_cheese_on_the_black_bowl_then_push_the_plate_to_the_front_of_the_stove_then_turn_on_the_stove_and_finally_put_the_black_bowl_on_top_of_t/registry_entry.yaml
- tasks/compose_243__put_the_cream_cheese_on_the_black_bowl_then_push_the_plate_to_the_front_of_the_stove_then_turn_on_the_stove_and_finally_open_the_middle_drawer_of_the/registry_entry.yaml
- tasks/compose_244__put_the_cream_cheese_on_the_black_bowl_then_push_the_plate_to_the_front_of_the_stove_then_open_the_middle_drawer_of_the_cabinet_and_finally_put_the_bl/registry_entry.yaml
- tasks/compose_245__put_the_cream_cheese_on_the_black_bowl_then_push_the_plate_to_the_front_of_the_stove_then_open_the_middle_drawer_of_the_cabinet_and_finally_put_the_bl/registry_entry.yaml
- tasks/compose_246__put_the_cream_cheese_on_the_black_bowl_then_turn_on_the_stove_then_open_the_middle_drawer_of_the_cabinet_and_finally_put_the_black_bowl_on_the_stove/registry_entry.yaml
- tasks/compose_247__put_the_cream_cheese_on_the_black_bowl_then_turn_on_the_stove_then_open_the_middle_drawer_of_the_cabinet_and_finally_put_the_black_bowl_on_top_of_the/registry_entry.yaml
- tasks/compose_248__put_the_wine_bottle_on_top_of_the_cabinet_then_push_the_plate_to_the_front_of_the_stove_then_turn_on_the_stove_and_finally_put_the_black_bowl_on_the_s/registry_entry.yaml
- tasks/compose_249__put_the_wine_bottle_on_top_of_the_cabinet_then_push_the_plate_to_the_front_of_the_stove_then_turn_on_the_stove_and_finally_open_the_middle_drawer_of_t/registry_entry.yaml
- tasks/compose_250__put_the_wine_bottle_on_top_of_the_cabinet_then_push_the_plate_to_the_front_of_the_stove_then_open_the_middle_drawer_of_the_cabinet_and_finally_put_the/registry_entry.yaml
- tasks/compose_251__put_the_wine_bottle_on_top_of_the_cabinet_then_turn_on_the_stove_then_open_the_middle_drawer_of_the_cabinet_and_finally_put_the_black_bowl_on_the_stov/registry_entry.yaml
- tasks/compose_252__push_the_plate_to_the_front_of_the_stove_then_turn_on_the_stove_then_open_the_middle_drawer_of_the_cabinet_and_finally_put_the_black_bowl_on_the_stove/registry_entry.yaml
- tasks/compose_253__push_the_plate_to_the_front_of_the_stove_then_turn_on_the_stove_then_open_the_middle_drawer_of_the_cabinet_and_finally_put_the_black_bowl_on_top_of_th/registry_entry.yaml
- tasks/compose_254__put_the_black_bowl_on_the_plate_and_then_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_255__put_the_wine_bottle_on_the_rack_and_then_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_256__open_the_top_drawer_and_put_the_black_bowl_inside_and_then_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_257__put_the_wine_bottle_on_top_of_the_cabinet_and_then_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_258__push_the_plate_to_the_front_of_the_stove_and_then_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_259__turn_on_the_stove_and_then_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_260__put_the_black_bowl_on_the_stove_and_then_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_261__put_the_black_bowl_on_top_of_the_cabinet_and_then_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_262__open_the_middle_drawer_of_the_cabinet_and_then_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_263__put_the_black_bowl_on_the_plate_then_put_the_wine_bottle_on_the_rack_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_264__put_the_black_bowl_on_the_plate_then_put_the_wine_bottle_on_top_of_the_cabinet_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_265__put_the_black_bowl_on_the_plate_then_push_the_plate_to_the_front_of_the_stove_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_266__put_the_black_bowl_on_the_plate_then_turn_on_the_stove_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_267__put_the_black_bowl_on_the_plate_then_open_the_middle_drawer_of_the_cabinet_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_268__put_the_wine_bottle_on_the_rack_then_open_the_top_drawer_and_put_the_black_bowl_inside_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_269__put_the_wine_bottle_on_the_rack_then_push_the_plate_to_the_front_of_the_stove_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_270__put_the_wine_bottle_on_the_rack_then_turn_on_the_stove_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_271__put_the_wine_bottle_on_the_rack_then_put_the_black_bowl_on_the_stove_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_272__put_the_wine_bottle_on_the_rack_then_put_the_black_bowl_on_top_of_the_cabinet_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_273__put_the_wine_bottle_on_the_rack_then_open_the_middle_drawer_of_the_cabinet_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_274__put_the_wine_bottle_on_top_of_the_cabinet_then_open_the_top_drawer_and_put_the_black_bowl_inside_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_275__push_the_plate_to_the_front_of_the_stove_then_open_the_top_drawer_and_put_the_black_bowl_inside_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_276__turn_on_the_stove_then_open_the_top_drawer_and_put_the_black_bowl_inside_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_277__open_the_middle_drawer_of_the_cabinet_then_open_the_top_drawer_and_put_the_black_bowl_inside_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_278__put_the_wine_bottle_on_top_of_the_cabinet_then_push_the_plate_to_the_front_of_the_stove_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_279__put_the_wine_bottle_on_top_of_the_cabinet_then_turn_on_the_stove_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_280__put_the_wine_bottle_on_top_of_the_cabinet_then_put_the_black_bowl_on_the_stove_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_281__put_the_wine_bottle_on_top_of_the_cabinet_then_open_the_middle_drawer_of_the_cabinet_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_282__push_the_plate_to_the_front_of_the_stove_then_turn_on_the_stove_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_283__push_the_plate_to_the_front_of_the_stove_then_put_the_black_bowl_on_the_stove_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_284__push_the_plate_to_the_front_of_the_stove_then_put_the_black_bowl_on_top_of_the_cabinet_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_285__push_the_plate_to_the_front_of_the_stove_then_open_the_middle_drawer_of_the_cabinet_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_286__turn_on_the_stove_then_put_the_black_bowl_on_the_stove_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_287__turn_on_the_stove_then_put_the_black_bowl_on_top_of_the_cabinet_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_288__turn_on_the_stove_then_open_the_middle_drawer_of_the_cabinet_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_289__open_the_middle_drawer_of_the_cabinet_then_put_the_black_bowl_on_the_stove_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_290__open_the_middle_drawer_of_the_cabinet_then_put_the_black_bowl_on_top_of_the_cabinet_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_291__put_the_black_bowl_on_the_plate_then_put_the_wine_bottle_on_the_rack_then_push_the_plate_to_the_front_of_the_stove_and_finally_put_the_cream_cheese_bo/registry_entry.yaml
- tasks/compose_292__put_the_black_bowl_on_the_plate_then_put_the_wine_bottle_on_the_rack_then_turn_on_the_stove_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_293__put_the_black_bowl_on_the_plate_then_put_the_wine_bottle_on_the_rack_then_open_the_middle_drawer_of_the_cabinet_and_finally_put_the_cream_cheese_box_i/registry_entry.yaml
- tasks/compose_294__put_the_black_bowl_on_the_plate_then_put_the_wine_bottle_on_top_of_the_cabinet_then_push_the_plate_to_the_front_of_the_stove_and_finally_put_the_cream/registry_entry.yaml
- tasks/compose_295__put_the_black_bowl_on_the_plate_then_put_the_wine_bottle_on_top_of_the_cabinet_then_turn_on_the_stove_and_finally_put_the_cream_cheese_box_in_the_bask/registry_entry.yaml
- tasks/compose_296__put_the_black_bowl_on_the_plate_then_put_the_wine_bottle_on_top_of_the_cabinet_then_open_the_middle_drawer_of_the_cabinet_and_finally_put_the_cream_ch/registry_entry.yaml
- tasks/compose_297__put_the_black_bowl_on_the_plate_then_push_the_plate_to_the_front_of_the_stove_then_turn_on_the_stove_and_finally_put_the_cream_cheese_box_in_the_baske/registry_entry.yaml
- tasks/compose_298__put_the_black_bowl_on_the_plate_then_push_the_plate_to_the_front_of_the_stove_then_open_the_middle_drawer_of_the_cabinet_and_finally_put_the_cream_che/registry_entry.yaml
- tasks/compose_299__put_the_black_bowl_on_the_plate_then_turn_on_the_stove_then_open_the_middle_drawer_of_the_cabinet_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_300__put_the_wine_bottle_on_the_rack_then_push_the_plate_to_the_front_of_the_stove_then_open_the_top_drawer_and_put_the_black_bowl_inside_and_finally_put_t/registry_entry.yaml
- tasks/compose_301__put_the_wine_bottle_on_the_rack_then_turn_on_the_stove_then_open_the_top_drawer_and_put_the_black_bowl_inside_and_finally_put_the_cream_cheese_box_in/registry_entry.yaml
- tasks/compose_302__put_the_wine_bottle_on_the_rack_then_open_the_middle_drawer_of_the_cabinet_then_open_the_top_drawer_and_put_the_black_bowl_inside_and_finally_put_the/registry_entry.yaml
- tasks/compose_303__put_the_wine_bottle_on_the_rack_then_push_the_plate_to_the_front_of_the_stove_then_turn_on_the_stove_and_finally_put_the_cream_cheese_box_in_the_baske/registry_entry.yaml
- tasks/compose_304__put_the_wine_bottle_on_the_rack_then_push_the_plate_to_the_front_of_the_stove_then_put_the_black_bowl_on_the_stove_and_finally_put_the_cream_cheese_bo/registry_entry.yaml
- tasks/compose_305__put_the_wine_bottle_on_the_rack_then_push_the_plate_to_the_front_of_the_stove_then_put_the_black_bowl_on_top_of_the_cabinet_and_finally_put_the_cream/registry_entry.yaml
- tasks/compose_306__put_the_wine_bottle_on_the_rack_then_push_the_plate_to_the_front_of_the_stove_then_open_the_middle_drawer_of_the_cabinet_and_finally_put_the_cream_che/registry_entry.yaml
- tasks/compose_307__put_the_wine_bottle_on_the_rack_then_turn_on_the_stove_then_put_the_black_bowl_on_the_stove_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_308__put_the_wine_bottle_on_the_rack_then_turn_on_the_stove_then_put_the_black_bowl_on_top_of_the_cabinet_and_finally_put_the_cream_cheese_box_in_the_baske/registry_entry.yaml
- tasks/compose_309__put_the_wine_bottle_on_the_rack_then_turn_on_the_stove_then_open_the_middle_drawer_of_the_cabinet_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_310__put_the_wine_bottle_on_the_rack_then_open_the_middle_drawer_of_the_cabinet_then_put_the_black_bowl_on_the_stove_and_finally_put_the_cream_cheese_box_i/registry_entry.yaml
- tasks/compose_311__put_the_wine_bottle_on_the_rack_then_open_the_middle_drawer_of_the_cabinet_then_put_the_black_bowl_on_top_of_the_cabinet_and_finally_put_the_cream_che/registry_entry.yaml
- tasks/compose_312__put_the_wine_bottle_on_top_of_the_cabinet_then_push_the_plate_to_the_front_of_the_stove_then_open_the_top_drawer_and_put_the_black_bowl_inside_and_fin/registry_entry.yaml
- tasks/compose_313__put_the_wine_bottle_on_top_of_the_cabinet_then_turn_on_the_stove_then_open_the_top_drawer_and_put_the_black_bowl_inside_and_finally_put_the_cream_chee/registry_entry.yaml
- tasks/compose_314__put_the_wine_bottle_on_top_of_the_cabinet_then_open_the_middle_drawer_of_the_cabinet_then_open_the_top_drawer_and_put_the_black_bowl_inside_and_finall/registry_entry.yaml
- tasks/compose_315__push_the_plate_to_the_front_of_the_stove_then_turn_on_the_stove_then_open_the_top_drawer_and_put_the_black_bowl_inside_and_finally_put_the_cream_chees/registry_entry.yaml
- tasks/compose_316__push_the_plate_to_the_front_of_the_stove_then_open_the_middle_drawer_of_the_cabinet_then_open_the_top_drawer_and_put_the_black_bowl_inside_and_finally/registry_entry.yaml
- tasks/compose_317__turn_on_the_stove_then_open_the_middle_drawer_of_the_cabinet_then_open_the_top_drawer_and_put_the_black_bowl_inside_and_finally_put_the_cream_cheese_b/registry_entry.yaml
- tasks/compose_318__put_the_wine_bottle_on_top_of_the_cabinet_then_push_the_plate_to_the_front_of_the_stove_then_turn_on_the_stove_and_finally_put_the_cream_cheese_box_in/registry_entry.yaml
- tasks/compose_319__put_the_wine_bottle_on_top_of_the_cabinet_then_push_the_plate_to_the_front_of_the_stove_then_put_the_black_bowl_on_the_stove_and_finally_put_the_cream/registry_entry.yaml
- tasks/compose_320__put_the_wine_bottle_on_top_of_the_cabinet_then_push_the_plate_to_the_front_of_the_stove_then_open_the_middle_drawer_of_the_cabinet_and_finally_put_the/registry_entry.yaml
- tasks/compose_321__put_the_wine_bottle_on_top_of_the_cabinet_then_turn_on_the_stove_then_put_the_black_bowl_on_the_stove_and_finally_put_the_cream_cheese_box_in_the_bask/registry_entry.yaml
- tasks/compose_322__put_the_wine_bottle_on_top_of_the_cabinet_then_turn_on_the_stove_then_open_the_middle_drawer_of_the_cabinet_and_finally_put_the_cream_cheese_box_in_th/registry_entry.yaml
- tasks/compose_323__put_the_wine_bottle_on_top_of_the_cabinet_then_open_the_middle_drawer_of_the_cabinet_then_put_the_black_bowl_on_the_stove_and_finally_put_the_cream_ch/registry_entry.yaml
- tasks/compose_324__push_the_plate_to_the_front_of_the_stove_then_turn_on_the_stove_then_put_the_black_bowl_on_the_stove_and_finally_put_the_cream_cheese_box_in_the_baske/registry_entry.yaml
- tasks/compose_325__push_the_plate_to_the_front_of_the_stove_then_turn_on_the_stove_then_put_the_black_bowl_on_top_of_the_cabinet_and_finally_put_the_cream_cheese_box_in/registry_entry.yaml
- tasks/compose_326__push_the_plate_to_the_front_of_the_stove_then_turn_on_the_stove_then_open_the_middle_drawer_of_the_cabinet_and_finally_put_the_cream_cheese_box_in_the/registry_entry.yaml
- tasks/compose_327__push_the_plate_to_the_front_of_the_stove_then_open_the_middle_drawer_of_the_cabinet_then_put_the_black_bowl_on_the_stove_and_finally_put_the_cream_che/registry_entry.yaml
- tasks/compose_328__push_the_plate_to_the_front_of_the_stove_then_open_the_middle_drawer_of_the_cabinet_then_put_the_black_bowl_on_top_of_the_cabinet_and_finally_put_the/registry_entry.yaml
- tasks/compose_329__turn_on_the_stove_then_open_the_middle_drawer_of_the_cabinet_then_put_the_black_bowl_on_the_stove_and_finally_put_the_cream_cheese_box_in_the_basket/registry_entry.yaml
- tasks/compose_330__turn_on_the_stove_then_open_the_middle_drawer_of_the_cabinet_then_put_the_black_bowl_on_top_of_the_cabinet_and_finally_put_the_cream_cheese_box_in_the/registry_entry.yaml
- tasks/compose_331__open_the_top_drawer_then_put_the_black_bowl_inside_the_open_top_drawer_and_finally_close_the_top_drawer/registry_entry.yaml
- tasks/compose_332__open_the_top_drawer_then_put_the_black_bowl_inside_the_open_top_drawer_then_close_the_top_drawer_and_finally_open_the_middle_drawer_of_the_cabinet/registry_entry.yaml
- tasks/compose_333__turn_on_the_first_stove_then_put_the_moka_pot_on_the_first_stove_and_finally_move_the_moka_pot_to_the_other_stove/registry_entry.yaml
- tasks/compose_334__turn_on_the_second_stove_then_put_the_moka_pot_on_the_second_stove_and_finally_move_the_moka_pot_to_the_other_stove/registry_entry.yaml
- tasks/compose_335__put_the_black_bowl_in_the_bottom_drawer_of_the_left_white_cabinet_and_then_close_the_bottom_drawer_of_the_left_white_cabinet/registry_entry.yaml
- tasks/compose_336__put_the_black_bowl_in_the_bottom_drawer_of_the_left_white_cabinet_and_then_put_the_wine_bottle_on_top_of_the_right_wooden_cabinet/registry_entry.yaml
- tasks/compose_337__put_the_black_bowl_in_the_bottom_drawer_of_the_left_white_cabinet_then_close_the_bottom_drawer_of_the_left_white_cabinet_and_finally_open_the_top_draw/registry_entry.yaml
- tasks/compose_338__put_the_black_bowl_in_the_bottom_drawer_of_the_left_white_cabinet_then_close_the_bottom_drawer_of_the_left_white_cabinet_and_finally_open_the_middle_d/registry_entry.yaml
- tasks/compose_339__put_the_black_bowl_in_the_bottom_drawer_of_the_left_white_cabinet_then_close_the_bottom_drawer_of_the_left_white_cabinet_and_finally_put_the_wine_bott/registry_entry.yaml
- tasks/compose_340__put_the_black_bowl_in_the_bottom_drawer_of_the_left_white_cabinet_then_close_the_bottom_drawer_of_the_left_white_cabinet_and_finally_put_the_wine_bott/registry_entry.yaml
- tasks/compose_341__put_the_black_bowl_in_the_bottom_drawer_of_the_left_white_cabinet_then_close_the_bottom_drawer_of_the_left_white_cabinet_then_open_the_top_drawer_of_t/registry_entry.yaml
- tasks/compose_342__put_the_black_bowl_in_the_bottom_drawer_of_the_left_white_cabinet_then_close_the_bottom_drawer_of_the_left_white_cabinet_then_open_the_top_drawer_of_t/registry_entry.yaml
- tasks/compose_343__put_the_black_bowl_in_the_bottom_drawer_of_the_left_white_cabinet_then_close_the_bottom_drawer_of_the_left_white_cabinet_then_open_the_top_drawer_of_t/registry_entry.yaml
- tasks/compose_344__put_the_black_bowl_in_the_bottom_drawer_of_the_left_white_cabinet_then_close_the_bottom_drawer_of_the_left_white_cabinet_then_open_the_middle_drawer_o/registry_entry.yaml
- tasks/compose_345__put_the_black_bowl_in_the_bottom_drawer_of_the_left_white_cabinet_then_close_the_bottom_drawer_of_the_left_white_cabinet_then_open_the_middle_drawer_o/registry_entry.yaml
- tasks/compose_346__put_the_white_mug_on_the_left_plate_then_put_the_yellow_and_white_mug_on_the_right_plate_and_finally_put_the_chocolate_pudding_to_the_right_of_the_add/registry_entry.yaml
- tasks/compose_347__put_the_white_mug_on_the_left_plate_then_put_the_yellow_and_white_mug_on_the_right_plate_and_finally_put_the_chocolate_pudding_on_the_added_plate/registry_entry.yaml
- tasks/compose_348__put_the_white_mug_on_the_left_plate_then_put_the_yellow_and_white_mug_on_the_right_plate_then_put_the_chocolate_pudding_to_the_right_of_the_added_plat/registry_entry.yaml
- tasks/compose_349__put_the_white_mug_on_the_left_plate_then_put_the_yellow_and_white_mug_on_the_right_plate_then_put_the_chocolate_pudding_on_the_added_plate_and_finally/registry_entry.yaml
- tasks/compose_350__put_the_right_moka_pot_on_the_stove_then_put_the_left_moka_pot_on_the_stove_and_finally_turn_on_the_stove/registry_entry.yaml
